// <copyright file="Program.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// This file is generated by template.

using CloudScripting.Sample;
using Microsoft.ApplicationInsights.Channel;
using Microsoft.Mesh.CloudScripting;
using Microsoft.Mesh.CloudScripting.Common;

// Configure the host builder
var hostBuilder = Host.CreateDefaultBuilder(args)
    .ConfigureServices((hostBuilderContext, services) =>
    {
        var hostingEnv = hostBuilderContext.HostingEnvironment;
        var isUnityLocalDev = hostingEnv.IsUnityLocalDevelopment();
        var useAppInsights = isUnityLocalDev;

        services
            .AddCloudScriptingApplication()
            .AddHostedService<App>()
            .AddLogging(loggingBuilder =>
            {
                if (!useAppInsights)
                {
                    loggingBuilder
                        .AddJsonConsole();
                }
            });

        if (useAppInsights)
        {
            // Create the telemetry channel
            if (isUnityLocalDev)
            {
                services.AddSingleton<ITelemetryChannel>(
                    new InMemoryChannel()
                    {
                        DeveloperMode = true,
                    });
            }

            services
                .AddApplicationInsightsTelemetryWorkerService();
        }
    });

// Build the host
using IHost host = hostBuilder.Build();

// Run the host
host.Run();