//
// This file was auto-generated from ScriptGraphAsset assets in Unity Project Mesh201.
//

// <auto-generated />

namespace Microsoft.Mesh.CloudScripting
{
    using System;
    using System.Linq;
    using System.Numerics;
    using Microsoft.Mesh.CloudScripting;
    using Microsoft.Mesh.CloudScripting.Declarations;

    [UserCreatable(false)]
    public class ButtonBaseBehaviorVisualScript : VisualScriptNode
    {
        protected ButtonBaseBehaviorVisualScript(in Guid ahandle, bool transfer)
        : base(ahandle, transfer)
        { }

        internal static ButtonBaseBehaviorVisualScript GetOrCreateInstance(in Guid cookie, bool transfer)
        {
            var result = GetOrCreateCloudObject(
                cookie,
                transfer,
                (handle, t) => new ButtonBaseBehaviorVisualScript(handle, transfer: t));

            return result as ButtonBaseBehaviorVisualScript;
        }
    }
}