//
// This file was auto-generated from ScriptGraphAsset assets in Unity Project Mesh201.
//

// <auto-generated />

namespace Microsoft.Mesh.CloudScripting
{
    using System;
    using System.Linq;
    using System.Numerics;
    using Microsoft.Mesh.CloudScripting;
    using Microsoft.Mesh.CloudScripting.Declarations;

    [UserCreatable(false)]
    public class GlobeWeatherMarkersVisualScript : VisualScriptNode
    {
        protected GlobeWeatherMarkersVisualScript(in Guid ahandle, bool transfer)
        : base(ahandle, transfer)
        { }

        public event EventHandler<PropertyChangedBaseEventArgs> MaxSingleClickLengthChanged
        {
            add => AddPropertyChangedEventHandler(nameof(MaxSingleClickLength), value);
            remove => RemovePropertyChangedEventHandler(nameof(MaxSingleClickLength), value);
        }

        public event EventHandler<PropertyChangedBaseEventArgs> SelectionDistanceChanged
        {
            add => AddPropertyChangedEventHandler(nameof(SelectionDistance), value);
            remove => RemovePropertyChangedEventHandler(nameof(SelectionDistance), value);
        }

        public event EventHandler<PropertyChangedBaseEventArgs> ExistingCoordChanged
        {
            add => AddPropertyChangedEventHandler(nameof(ExistingCoord), value);
            remove => RemovePropertyChangedEventHandler(nameof(ExistingCoord), value);
        }

        public event EventHandler<PropertyChangedBaseEventArgs> MarkerPositionChanged
        {
            add => AddPropertyChangedEventHandler(nameof(MarkerPosition), value);
            remove => RemovePropertyChangedEventHandler(nameof(MarkerPosition), value);
        }

        [Replication(ReplicationKind.Full)]
        [Serialized(true)]
        public float MaxSingleClickLength
        {
            get => (float)this[nameof(MaxSingleClickLength)];
            set => this[nameof(MaxSingleClickLength)].SetValue(value);
        }

        [Replication(ReplicationKind.Full)]
        [Serialized(true)]
        public float SelectionDistance
        {
            get => (float)this[nameof(SelectionDistance)];
            set => this[nameof(SelectionDistance)].SetValue(value);
        }

        [Replication(ReplicationKind.Full)]
        [Serialized(true)]
        public Vector2 ExistingCoord
        {
            get => (Vector2)this[nameof(ExistingCoord)];
            set => this[nameof(ExistingCoord)].SetValue(value);
        }

        [Replication(ReplicationKind.Full)]
        [Serialized(true)]
        public Vector3 MarkerPosition
        {
            get => (Vector3)this[nameof(MarkerPosition)];
            set => this[nameof(MarkerPosition)].SetValue(value);
        }

        internal static GlobeWeatherMarkersVisualScript GetOrCreateInstance(in Guid cookie, bool transfer)
        {
            var result = GetOrCreateCloudObject(
                cookie,
                transfer,
                (handle, t) => new GlobeWeatherMarkersVisualScript(handle, transfer: t));

            return result as GlobeWeatherMarkersVisualScript;
        }
    }
}