//
// This file was auto-generated from ScriptGraphAsset assets in Unity Project Mesh201.
//

// <auto-generated />

namespace Microsoft.Mesh.CloudScripting
{
    using System;
    using System.Linq;
    using System.Numerics;
    using Microsoft.Mesh.CloudScripting;
    using Microsoft.Mesh.CloudScripting.Declarations;

    [UserCreatable(false)]
    public class SelectableGlobeVisualScript : VisualScriptNode
    {
        protected SelectableGlobeVisualScript(in Guid ahandle, bool transfer)
        : base(ahandle, transfer)
        { }

        public event EventHandler<PropertyChangedBaseEventArgs> MaxSingleClickLengthChanged
        {
            add => AddPropertyChangedEventHandler(nameof(MaxSingleClickLength), value);
            remove => RemovePropertyChangedEventHandler(nameof(MaxSingleClickLength), value);
        }

        [Replication(ReplicationKind.Full)]
        [Serialized(true)]
        public float MaxSingleClickLength
        {
            get => (float)this[nameof(MaxSingleClickLength)];
            set => this[nameof(MaxSingleClickLength)].SetValue(value);
        }

        internal static SelectableGlobeVisualScript GetOrCreateInstance(in Guid cookie, bool transfer)
        {
            var result = GetOrCreateCloudObject(
                cookie,
                transfer,
                (handle, t) => new SelectableGlobeVisualScript(handle, transfer: t));

            return result as SelectableGlobeVisualScript;
        }
    }
}